In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [6]:
from sklearn.datasets import load_iris
iris = load_iris()

In [12]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)

In [15]:
df['target'] = iris.target

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.3)

### logistic_regression

In [38]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9333333333333333

### SVM

In [39]:
svm = SVC(gamma='auto')
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9555555555555556

### RAndomForest

In [40]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9333333333333333

In [59]:
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt.score(x_test,y_test)

1.0

### KFold

In [41]:
from sklearn.model_selection import KFold
kf = KFold()
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [42]:
for train_index, test_index in kf.split([0,1,2,3,4,5,6,7,8]):
    print(train_index,test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


### Using KFold for our iris dataset

In [47]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [48]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold()

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(iris.data,iris.target):
    x_train,x_test,y_train,y_test = iris.data[train_index],iris.data[test_index],iris.target[train_index],iris.target[test_index]
    
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), x_train, x_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))
    

In [49]:
from sklearn.model_selection import cross_val_score

In [51]:
l_score = cross_val_score(LogisticRegression(),iris.data,iris.target)
l_score

C:\Users\angad\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [53]:
np.average(l_score)

0.9733333333333334

In [54]:
s_score = cross_val_score(SVC(),iris.data,iris.target)
s_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [55]:
np.average(s_score)

0.9666666666666666

In [56]:
d_score = cross_val_score(RandomForestClassifier(),iris.data,iris.target)
d_score

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [57]:
np.average(d_score)

0.9666666666666668

In [60]:
dt_score = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
dt_score

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [61]:
np.average(dt_score)

0.9666666666666668